### PR TITLE
UFL change : New feature : Nolibox (Nonlinear box)

### PR DESCRIPTION
**Pull request by nbouziani**
UFL change : New feature : Nolibox (Nonlinear box)

### CODE REVIEW

**Comment by pefarrell** [comment]
Could you please explain what this feature is for?

**Comment by nbouziani** [comment]
@dham : I have added the new Nolibox object which stands for Non Linear Box

**Comment by nbouziani** [comment]
Ah yes sorry, the purpose of the Nolibox object is to make possible the importation of exterior functions in Firedrake.

**Comment by pefarrell** [comment]
I don't understand, yet. Could you please give some examples of the kinds of exterior functions you want to import?

**Comment by wence-** [comment]
Something is wrong here. I would expect only one new file ( in the ufl subdirectory), but you seem to have added a bunch of new ones as well. 

Other comments: the name NoliBox is not at all descriptive. I guess this is an opaque object that knows how to evaluate itself at runtime, but only reports some symbolic information? A"boxed" nonlinear expression?

Can we bikeshed then name, and then add some class documentation to the resulting new object?

Minor points: prefer descriptor branch names (you can namespace with nacime/branch-name). This makes it easier to follow what's happening when more than one branch is in flight. 

Although GitHub offers a web based file upload and editing facility, I am it sure it is likely the most efficient. Irrespective, please write slightly more descriptive commit messages that describe the content/intent of the change a little

**Comment by dham** [comment]
This PR is rather broken. I'm going to close it.

**Pull request closed without merging**
